Repository Stark-Tech-Group/stg-sdk-golang, pull requests merged in 2023-08, with the labels that each got.

#90 feature/TSP-5475_GetControlByName
  docker/timescaledb.Dockerfile
  go.mod
  go.sum
  pkg/starkapi/api-client.go
  pkg/starkapi/client.go
  pkg/starkapi/forms_api.go
  pkg/starkapi/forms_api_test.go
  pkg/starkapi/mock-client_test.go
Labels: enhancement

#92 feature/TSP-5474_CreateFromControlOnTargetRef
  go.mod
  go.sum
  pkg/domain/form_control.go
  pkg/domain/form_control_test.go
  pkg/starkapi/forms_api.go
  pkg/starkapi/forms_api_test.go
Labels: enhancement

#94 feature/TSP-5612_VersionType
  pkg/domain/form_control.go
  pkg/domain/form_control_ref.go
  pkg/domain/form_control_ref_test.go
  pkg/starkapi/forms_api.go
  pkg/starkapi/forms_api_test.go
Labels: bug

#95 add equipType
  pkg/starkapi/auth_api_test.go
  pkg/starkapi/equip_api_test.go
  pkg/starkapi/query-params.go
  pkg/starkapi/query-params_test.go
Labels: enhancement

#96 Feature/tsp 5669 batch param
  .github/workflows/_build.yml
  go.mod
  go.sum
  pkg/domain/telemetry-message_test.go
  pkg/starkapi/cast_test.go
  pkg/starkapi/point_api_test.go
  pkg/starkapi/query-params.go
  pkg/starkapi/query-params_test.go
Labels: enhancement, dependencies

#98 feature/TSP-5574
  pkg/domain/audit_log.go
  pkg/starkapi/assets_api.go
  pkg/starkapi/assets_api_test.go
Labels: enhancement
